<?xml version="1.0" ?>
<definitions name="UniVerwaltung"
             targetNamespace="http://webkemper1.informatik.tu-muenchen.de/UniVerwaltung.wsdl"         
             xmlns:tns="http://webkemper1.informatik.tu-muenchen.de/UniVerwaltung.wsdl"                              
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"             
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns="http://schemas.xmlsoap.org/wsdl/">


  <message name="GetLehrUmfangVonProfessorRequest">
    <part name="ProfName" type="xsd:string"/>
  </message>
  <message name="GetLehrUmfangVonProfessorResponse">
    <part name="LehrUmfang" type="xsd:int"/>
  </message>

  <portType name="UniVerwaltungPortType">
    <operation name="getLehrUmfangVonProfessor">
      <input message="tns:GetLehrUmfangVonProfessorRequest"/>
      <output message="tns:GetLehrUmfangVonProfessorResponse"/>
    </operation>
  </portType>

  <binding name="UniVerwaltungSOAPBinding" type="tns:UniVerwaltungPortType">
    <soap:binding style="rpc"
                  transport="http://schemas.xmlsoap.org/soap/http"/>

    <operation name="getLehrUmfangVonProfessor">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="encoded"  namespace="UniVerwaltung"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </input>
      <output>
        <soap:body use="encoded"  namespace="UniVerwaltung"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </output>
    </operation>
  </binding>

  <service name="UniVerwaltungService">
    <port name="UniVerwaltung" binding="tns:UniVerwaltungSOAPBinding">
      <soap:address location="http://webkemper1.informatik.tu-muenchen.de/UniVerwaltung"/> 
    </port>
  </service>

</definitions>

